services:

  app:
    build: ./server

    ports:
      - "5000:5000"

    container_name: study-room-container
    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

  
  monitor:
    build:
      context: ./server
      dockerfile: Dockerfile.monitor
    container_name: monitor-service
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  
  controller:
    build:
      context: ./server
      dockerfile: Dockerfile.controller
    container_name: controller-service
    ports:
      - "4000:4000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
volumes:
   grafana-storage: